AWSTemplateFormatVersion: 2010-09-09
Description: TaxServiceLambda
Transform:
  - AWS::Serverless-2016-10-31

Resources:
  putItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-item.putItemHandler
      Runtime: nodejs20.x
      MemorySize: 128
      Timeout: 100
      Description: A function to upload documents to an S3 bucket.
      Policies:
        # IAM policy granting required S3 permissions
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3Bucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  # Define the S3 bucket resource
  S3Bucket:
    Type: AWS::S3::Bucket

# ... other configurations ...

Globals:
  Function:
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
